version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "23:30"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: "@testing-library/user-event"
    versions:
    - 12.7.0
    - 12.8.0
    - 13.0.0
    - 13.0.13
    - 13.0.16
    - 13.0.2
    - 13.1.1
    - 13.1.2
    - 13.1.5
  - dependency-name: react-scripts
    versions:
    - 4.0.2
